security:
    providers:
        # used to reload user from session & other features (e.g. switch_user)
        app_user_provider:
            entity:
                class: App\Entity\User
                property: email
    firewalls:
        # Firewall qui intercepte la route de login API
        login:
            pattern: ^/api/login
            stateless: true
            json_login:
                check_path: /api/login_check
                username_path: email
                password_path: password
                success_handler: lexik_jwt_authentication.handler.authentication_success
                failure_handler: lexik_jwt_authentication.handler.authentication_failure

        # Firewall qui gere les routes de l'API
        api:
            pattern:   ^/api/
            stateless: true
            jwt: ~
        
        # Routes de dev
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false

        # Toutes les autres du projet (l'appli HTML O'flix front/back)
        

            # activate different ways to authenticate
            # https://symfony.com/doc/current/security.html#the-firewall
            
                
            # https://symfony.com/doc/current/security/impersonating_user.html
            # switch_user: true

    # Easy way to control access for large sections of your site
    # Note: Only the *first* access control that matches will be used
  
    # Pas besoin de PUBLIC_ACCESS sur les chemin en accès libre
        
        # - { path: ^/profile, roles: ROLE_USER }

